export const quotes = [
  "Acknowledge me",
  "I'm a real gangster",
  "I run conglomerates",
  "Without me a organisation big enough to be on the NASDAQ goes belly up",
  "I am the one who knocks",
  "Look at me, I'm the captain now",
  "I'm the final boss",
  "I'm a profressional driver",
  "I'm a profressional chef",
  "I run empires",
  "I run this house",
  "I'm going to buy Beverly Hills",
  "MAGA",
  "Trump is the best",
  "Trump is the best president in history",
  "Vote Reform",
  "I'm the baddest motherfucker of all time",
  "I'm the crack head whisperer",
  "Disgusting",
  "I ain't got time",
  "Well done",
  "Dossers",
  "Hehehe",
  "I'm a proper hard kunt",
  "You think I'm a fuckin joke?",
  "I'll show you what a joke is",
  "I'm a ganster",
  "Don't wanna fuck with me",
];
